Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://reichardt.uoregon.edu:3000"
  copyright: nlab 2012
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
